### PR TITLE
Add new package maintainer

### PR DESCRIPTION
**Pull request by aarondettmann**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aarondettmann** [comment]
See https://github.com/conda-forge/ambiance-feedstock/issues/4 -- I hope adding the user name is sufficient in this case. I still have to get a more familiar with the tooling used to create Conda packages.

**Comment by bryanwweber** [comment]
@conda-forge-admin please rerender

**Comment by bryanwweber** [comment]
@aarondettmann This looks good! I've asked the conda forge bot to "rerender" the recipe, which just updates any build-time stuff that conda-forge have updated upstream. It won't affect this PR. Thanks for adding yourself!

**Review by bryanwweber — APPROVED** [review]

**Comment by aarondettmann** [comment]
Thank you, @bryanwweber

**Pull request merged**
